# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/postgres:9.5.6
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=rails-studies_test

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
              bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Set up DB
          command: bundle exec rake db:migrate
          environment:
              DATABASE_URL: "postgres://ubuntu@localhost:5432/rails-studies_test"

      - run:
          name: run tests
          command: rails t